### ISSUE TITLE
Release version 1.0.0?

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/gettext-setup-gem#73]
## Use Case

semantic versioning says that APIs at version 1.0.0 and above can be considered stable. Since this gem is used in many other production applications, like r10k, please release it as 1.0.0.

## Describe the Solution You Would Like

I need a 1.0.0 release. Many orgs have a 'no-beta/no-unstable' software policy.

## Describe Alternatives You've Considered

There are no suitable alternatives

**Comment by smcclellan** [comment]
Version 1.0 has been released; that release was cross-released as version 0.32 to avoid a myriad dependency bumps in several projects. We will be releasing on the 1.x line going forward, minus the patch in 0.34.

**Comment by bastelfreak** [comment]
Hi @smcclellan. I just noticed that the 1.0 release got yanked from rubygems.org. Could you explain that?

**Comment by smcclellan** [comment]
Hi @bastelfreak; after releasing the 1.0 gem, we found several internal dependency issues for us in Puppet Enterprise. It being close to a PE release, we opted to yank the gem in the short term and will release 1.1 next week. I apologize for the inconvenience!

**Comment by bastelfreak** [comment]
hey people. what's the status here?

**Comment by smcclellan** [comment]
Hi @bastelfreak! @steveax may be able to provide more info for you here, as I am no longer maintaining the gem myself.

**Comment by bastelfreak** [comment]
Hey @steveax , do you have an update here?

**Comment by LukasAud** [comment]
I believe this gem has had a 1.1 release for over two years. This issue should be closed, @bastelfreak.
