### ISSUE TITLE
Seeing failure with 0.32 release:- private method `include' called for Object:Class (NoMethodError)

### ISSUE THREAD

**Issue by karelyatin** [puppetlabs/gettext-setup-gem#77]
## Describe the Bug
In some of our puppet jobs(on CentOS7) we are seeing below traceback after 0.32 installed last night, specifically with commit https://github.com/puppetlabs/gettext-setup-gem/commit/78f786ae8ac3c7c19e8d439f4a4241997a81f3a8.

+ r10k -v DEBUG puppetfile install
/tmp/puppet-openstack/.bundled_gems/gems/gettext-setup-0.32/lib/gettext-setup/gettext_setup.rb:28:in `initialize': private method `include' called for Object:Class (NoMethodError)
 from /tmp/puppet-openstack/.bundled_gems/gems/r10k-2.6.4/lib/r10k.rb:4:in `<module:R10K>'
 from /tmp/puppet-openstack/.bundled_gems/gems/r10k-2.6.4/lib/r10k.rb:3:in `<top (required)>'
 from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
 from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
 from /tmp/puppet-openstack/.bundled_gems/gems/r10k-2.6.4/lib/r10k/cli.rb:1:in `<top (required)>'
 from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
 from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
 from /tmp/puppet-openstack/.bundled_gems/gems/r10k-2.6.4/bin/r10k:3:in `<top (required)>'
 from /tmp/puppet-openstack/.bundled_gems/bin/r10k:23:in `load'
 from /tmp/puppet-openstack/.bundled_gems/bin/r10k:23:in `<main>'

## Expected Behavior
r10k setup should be successful, and if some version mismatch is there(some strict requirement missing) it should be indicated.

## Environment
 - Version - 0.32
 - Platform - CentOS 7
- Ruby version - 2.0.0

## Additional Context
Related Bug:- https://bugs.launchpad.net/tripleo/+bug/1859045/comments/2
Related Log:- https://61072da72249bc29a06c-8a3936d67b27dfc7deb137fd1cb55ee3.ssl.cf1.rackcdn.com/701500/1/check/puppet-openstack-integration-5-scenario001-tempest-centos-7-luminous/b446e38/job-output.txt

**Comment by smcclellan** [comment]
Thank you for filing; fixed in gettext-setup version 0.34.
